"""
Convex Hull Benchmark Plot

Dynamically reads all CSV files from output/ directory and generates timing plots.

Date: 29th April, 2026
This script was generated by Github Copilot.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import glob
import os

# Set style
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (14, 8)

# Find all CSV files in output/ directory
csv_files = glob.glob("output/*.csv")

if not csv_files:
    print("Error: No CSV files found in output/ directory!")
    exit(1)

print(f"Found {len(csv_files)} CSV file(s)")

# Create figure
fig, ax = plt.subplots(figsize=(14, 8))

# Define a color palette
colors = sns.color_palette("husl", len(csv_files))

# Plot each algorithm
for idx, csv_file in enumerate(sorted(csv_files)):
    df = pd.read_csv(csv_file)
    
    # Extract algorithm name from filename
    # Remove 'output/' and '.csv', then replace underscores with spaces
    algo_name = os.path.basename(csv_file)
    algo_name = algo_name.replace('.csv', '')
    algo_name = algo_name.replace('_', ' ')
    
    print(f"  Plotting: {algo_name}")
    
    # Plot CPU clock time
    ax.plot(df['PointCount'], df['AvgCPU_ms'], 
            marker='o', label=algo_name,
            linewidth=1.5, markersize=2, color=colors[idx], alpha=0.8)

ax.set_xlabel('Number of Points', fontsize=13, fontweight='bold')
ax.set_ylabel('Average Execution Time (ms)', fontsize=13, fontweight='bold')
ax.set_title('Convex Hull Algorithm Performance', fontsize=15, fontweight='bold')
ax.legend(fontsize=12, loc='best')
ax.grid(True, alpha=0.3)

plt.tight_layout()
output_file = "timing.png"
plt.savefig(output_file, dpi=150, bbox_inches='tight')
print(f"Plot saved to {output_file}")

print("Plotting completed successfully!")
